language: python
python:
- '3.6'
branches:
  only:
  - src
before_install:
  #installing pt lang pack
- sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-pt
script:
- make travis
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
  - secure: tZrDMxiOkqpEgWIBNLM0uqOn99TD1ScMcTyfOUgJaAoPkTwj+9TiCp5BlB0FcK2TQCYo63mnj/EsnODQkRVwmwSGdtdwajNC88aAKLsNq1UcU5funJTyVRhWkaGM2Y+/LDRHIgI0AO7IhP2oUqGI9oMTQSeSyvRv/jo7nDBiqT/KkOcTxekXonIcGEt/gDOTLTZyPyH7BPnBriOwqjCVcGqSOKijU1sE/zjG/VOkz1MbMCXFiEbHLrQXkkBOUJLrrddR81PrUiO9Q0r/1xhYx2fxvdo3aSlhED3mXanYKCnakv+ONRZfDBgKauy9bSUgncNdNl3KD0zRmrFSzF/6OBQmATq3nUfmVJUEHHMkmLuE7oSR/cceCdxmfzxIIPB150QlaSYhaKdafT27qQlOOjPlIsX82jORdjiXddmZC0PjhdJM2ZKl85YQIea0TyyDIWyafWvrcskfdWqGEJYa4yUdmhEeMNrSDD3MNK1KysYg/0bT3/+vKlGLPeRRiizDUxS+DiH96ICgOCwplHrvIpneHe7IxM7Avizjkp9LAoeexEVqh91JkDDnXWGzwq6Vfpj6kPrZffsVby1hdqmjVCLBuECDNUgPXKnOMVjrvuUzsV705xCn03OmeFBO89qAnnfP1b3rIu8Oh6jpBQ0IP66oHjL22a82UiUUyLsOlro=
